title: Estudio de vulnerabilidades y protocolos de seguridad en sistemas de inteligencia artificial
description: Trabajo Fin de Máster — MCAIS2 · Ildefonso González Sánchez · documento v1.0.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
baseurl: "/TFM-Offensive-Security-IAs"
url: "https://agentef0ns1.github.io"
lang: es

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-hacker.gemspec
  - LICENSE
  - .gitignore
  - README.md
  - vendor
  - node_modules
  - .bundle
  - tools
  - lab
  - informes
  - scripts

sass:
  style: compressed
